# RAG Configuration

# Directory Settings
output_dir: "output"  # Directory for processed files and dashboard output

# Embedding Model Settings
embedding_model: "sentence-transformers/all-MiniLM-L6-v2"

# Text Splitting Settings
chunk_size: 500
chunk_overlap: 100
separators: ["\n\n", "\n", " ", ""]

# Retrieval Settings
initial_k: 100  # Number of documents to retrieve initially
final_k: 15     # Number of documents to return after filtering
max_chunks_per_doc: 3  # Maximum number of chunks per document
exact_match_score: 0.9  # Score given to exact metadata matches

# Vector Store Settings
persist_directory: "vector_store"

# Metadata Fields for Exact Matching
exact_match_fields:
  - title
  - emotion
  - topic
  - tags

# Logging Settings
log_level: "INFO"
log_format: "%(asctime)s - %(levelname)s - %(message)s" 